dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"
          - "**/package-lock.json"
          - "**/pnpm-lock.yaml"
          - "**/yarn.lock"
          - "**/requirements*.txt"
          - "**/poetry.lock"
          - "**/go.mod"
          - "**/go.sum"

javascript:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.js"
          - "**/*.jsx"
          - "**/*.ts"
          - "**/*.tsx"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"
